### ISSUE TITLE
Uvicorn live reload possibly scanning unnecessary directories? 

### ISSUE THREAD

**Issue by takaf3** [madroidmaq/mlx-omni-server#1]
First of all, thank you for the amazing work! I was really looking for an mlx OpenAI api compatible server :)

---

When I was trying this out following the Quick Start, I noticed that my terminal started trying to access many directories (I was getting "Do you want to allow terminal to access xxx? pop up on my mac), like Contacts, Photos, Reminders etc. I stopped the server with ctrl + c, and the trace I see is as follows:

```
Traceback (most recent call last):
  File "/Users/takafumi/.venv_mlx/bin/mlx-omni-server", line 8, in <module>
    sys.exit(start())
             ^^^^^^^
  File "/Users/takafumi/.venv_mlx/lib/python3.11/site-packages/mlx_omni_server/main.py", line 23, in start
    uvicorn.run("mlx_omni_server.main:app", host="0.0.0.0", port=10240, reload=True)
  File "/Users/takafumi/.venv_mlx/lib/python3.11/site-packages/uvicorn/main.py", line 574, in run
    ChangeReload(config, target=server.run, sockets=[sock]).run()
  File "/Users/takafumi/.venv_mlx/lib/python3.11/site-packages/uvicorn/supervisors/basereload.py", line 52, in run
    for changes in self:
  File "/Users/takafumi/.venv_mlx/lib/python3.11/site-packages/uvicorn/supervisors/basereload.py", line 71, in __next__
    return self.should_restart()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/takafumi/.venv_mlx/lib/python3.11/site-packages/uvicorn/supervisors/statreload.py", line 31, in should_restart
    for file in self.iter_py_files():
  File "/Users/takafumi/.venv_mlx/lib/python3.11/site-packages/uvicorn/supervisors/statreload.py", line 51, in iter_py_files
    for path in list(reload_dir.rglob("*.py")):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 968, in rglob
    for p in selector.select_from(self):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 408, in _select_from
    for p in successor_select(starting_point, is_dir, exists, scandir):
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 355, in _select_from
    with scandir(parent_path) as scandir_it:
         ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.10/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 938, in _scandir
    return os.scandir(self)
           ^^^^^^^^^^^^^^^^
InterruptedError: [Errno 4] Interrupted system call: '/Users/takafumi/Library/Reminders'
```

I am not familiar with uvicorn unfortunately, but it is trying to scan directories for live reload? 

I see there's [`--reload-dir` option](https://www.uvicorn.org/settings/#development) to specify a directory to watch in uvicorn. I also see that if this is unset, it will watch the whole current directory. So I guess I can try running `mlx-omni-server start` in a directory other than my user home to avoid the popup for now 👀

Would that be possible to set `--reload-dir` to specify the directories that's only needed for live reload for mlx-omni-server use?

**Comment by madroidmaq** [comment]
Thank you for your feedback. This is due to me adding the reload parameter during the development stage, which should not be enabled in the official release, and I have already removed this parameter.

If you want to make a PR to the project or develop your own branch, you can start it with `mlx-omni-server start --reload` to monitor code changes, and I have also limited the file scanning range, which will only scan for changes in the content under the source code files.

I will release a new version soon.

**Comment by madroidmaq** [comment]
@takaf3 The new version has been released, and you can update the version using the following methods. If there are still issues, please let me know.

```
pip install -U mlx-omni-server
```

**Comment by takaf3** [comment]
Thank you for your prompt fix and sharing details!!! Appreciate it 🤩
